import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  header: {
    width: "100%",
    height: 50,
    flexDirection: "row",
    paddingLeft: 10,
    paddingRight: 35,
    marginTop: 10,
    justifyContent: "space-between",
    backgroundColor: "#202020",
    marginBottom: 20,
  },
  headerImage: {
    width: 45,
    height: 45,
    borderRadius: 14,
  },
  location: {
    fontSize: 12,
    color: "#B7B7B7",
    fontFamily: "SoraRegular",
  },
  mainLocation: {
    fontSize: 14,
    fontFamily: "SoraMedium",
    fontWeight: "600",
    color: "#DDDDDD",
  },
  searchContainer: {
    width: "100%",
    alignItems: "center",
    backgroundColor: "#F9F9F9",
    paddingBottom:70,
  },
  inputContainer: {
    width: 315,
    height: 48,
    backgroundColor: "#313131",
    justifyContent: "space-between",
    flexDirection: "row",
    borderRadius: 16,
    alignItems: "center",
    paddingLeft: 16,
    paddingRight: 16,
  },
  topContainer: {
    width: "100%",
    alignItems: "center",
    backgroundColor: "#202020",
    height: 130,
  },
  input: {
    width: 200,
    height: 48,
    borderRadius: 16,
    backgroundColor: "#313131",
    fontFamily: "SoraMedium",
  },
  iconContainer: {
    width: 40,
    height: 40,
    backgroundColor: "#C67C4E",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
  },
  buy_one: {
    width: 315,
    height: 150,
    borderRadius: 16,
    marginTop: -70,
  },
  tab: (activeCoffeeType, item) => ({
    //  paddingVertical: 6,
    //  paddingHorizontal: 12,
    marginRight: 8,
    borderRadius: 12,
    borderWidth: 1,
    paddingBottom: 10,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 10,
    borderWidth: 0,
    backgroundColor: activeCoffeeType === item ? "#C67C4E" : "white",
  }),
  tabText: (activeCoffeeType, item) => ({
    color: activeCoffeeType === item ? "white" : "#2F4B4E",
    fontFamily: "SoraMedium",
  }),
  coffeeCardsContainer: {
    width: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    paddingLeft: 30,
    paddingRight: 30,
    marginTop: 24,
    justifyContent: "space-between",
  },
  footer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    height: 70,
    backgroundColor: "white",
    borderRadius:24,
    paddingLeft:50,
    paddingRight:50,
    justifyContent:"space-between",
    alignItems:"center",
    flexDirection:"row"
  },
});

export default styles;
